### ISSUE TITLE
WARNING: REMOTE SSL CERT DID NOT MATCH EXPECTED (PINNED) SSL CERT

### ISSUE THREAD

**Issue by arminmacx** [robputt/Py-DNS-over-HTTPS-Proxy#2]
Hi @robputt796 ,

today I got this error and script exit for possible MITM attack. Can we change pinned cert that you attach before?

**Comment by robputt** [comment]
Hi @arminmacx,

Sorry I did not realise these SSL certs expired so frequently... I will make some monitoring to check if the SSL cert changes and for it to email me.

Anyway for now I have updated the script.

Best Regards,

Rob

**Comment by arminmacx** [comment]
Hi @robputt796 

its happened again
